# 测试配置文件
# @author <a href="https://github.com/liyupi">程序员鱼皮</a>
# @from <a href="https://yupi.icu">编程导航知识星球</a>
server:
  port: 8101
spring:
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.130.53.38:3306/yudada
    username: yudada
    password: KA8RWPeLX4jfDA3J
  # Redis 配置
  # todo 需替换配置
  redis:
    database: 1
    host: 8.130.53.38
    port: 6379
    timeout: 5000
    password: 97bc22b54b49d848
